org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

minecraft_version=1.21.1
minecraft_version_range=[1.21.1]

twilightforest_version=4.8.3345
twilightforest_version_range=[4.7.3196,)

neo_version=21.1.233
loader_version_range=[1,)

mod_id=acofi
mod_name=Alternate Create Of Fiery Items
mod_license=MIT
mod_version=1.2.0
mod_group_id=net.superfeda.acofi
