org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)

twilightforest_version=4.3.2145
twilightforest_version_range=[4.3.1735,)

forge_version=47.2.16
forge_version_range=[47,)
loader_version_range=[47,)

mapping_channel=official
mapping_version=1.20.1

mod_id=acofi
mod_name=ACOFI
mod_license=MIT
mod_version=1.2.0
mod_group_id=net.superfeda.acofi
mod_authors=SuperFeda
mod_description=ACOFI is a mod that changes the creation of fiery equipment from the Twilight Forest
